---

- name: cikube | play | Provision a generic node image
  hosts: default
  become: yes
  any_errors_fatal: yes
  roles:
    - dotinfra.cikube.utils
    - dotinfra.cikube.nerdctl
    - dotinfra.cikube.experience
    - dotinfra.cikube.raid_localssd
    - dotinfra.cikube.cikube_tools
    - dotinfra.cikube.k3s_base
    - dotinfra.cikube.sysctl
    - dotinfra.cikube.finalize
