clusters:
- cluster:
    certificate-authority-data: xyz
    server: https://1.2.3.4
  name: cikube-cluster
contexts:
- context:
    cluster: cikube-cluster
    user: cikube-oidc
  name: cikube-cluster
users:
- name: cikube-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://foo.bar
      - --oidc-client-id=foobar
      - --oidc-client-secret=REPLACEME_CLIENT_SECRET
      - --oidc-extra-scope=email
